### ISSUE TITLE
certificate-controller doesn't pass spec.issuerRef.name

### ISSUE THREAD

**Issue by evankanderson** [knative-sandbox/net-certmanager#197]
Originally filed here: https://github.com/knative/serving/issues/10966 by @andrijaperovic 

/kind bug

# What version of Knative?
0.20.0

# Expected Behavior
Certificates should be created properly from knative certificate-controller.

# Actual Behavior
certificates are not created properly due to spec.issuerRef.name not being passed correctly:
```
{"severity":"INFO","timestamp":"2021-03-16T19:18:16.316165634Z","logger":"certcontroller.certificate-controller.event-broadcaster","caller":"record/event.go:278","message":"Event(v1.ObjectReference{Kind:\"Certificate\", Namespace:\"kfserving-test\", Name:\"kfserving-test.custom.domain\", UID:\"49a706cb-bc02-4254-866b-f5716d9add02\", APIVersion:\"networking.internal.knative.dev/v1alpha1\", ResourceVersion:\"179970269\", FieldPath:\"\"}): type: 'Warning' reason: 'CreationFailed' Failed to create Cert-Manager Certificate kfserving-test.custom.domain/kfserving-test: admission webhook \"webhook.cert-manager.io\" denied the request: spec.issuerRef.name: Required value: must be specified","commit":"ffa73df","knative.dev/controller":"certificate-controller"}
```

Logs were obtained by running the following command:
```shell
kubectl logs networking-certmanager-5bf97dd895-69vqk -n knative-serving -c networking-certmanager
```
We are using `apiVersion: cert-manager.io/v1` with our `Certificate` resources.

# Steps to Reproduce the Problem
Follow the instructions on kfserving README to setup kfserving installation and test inference service:
https://github.com/kubeflow/kfserving#create-kfserving-test-inference-service

Istio Version: v1.7.3
k8s version: v1.19.6 running on AKS with Ubuntu 18.04.5 LTS
Knative Serving: v0.20.0
cert-manager version: v1.2.0
KF Serving: v0.5.0

**Comment by nak3** [comment]
/reopen

I guess it is not fixed.

**Comment by itsmurugappan** [comment]
This value comes from config-certmanager. If no issuer is specified in the config map currently this controller does not [default](https://github.com/knative-sandbox/net-certmanager/blob/3570d36160261cf581353b76efaad5c46e3d68e3/pkg/reconciler/certificate/config/cert_manager.go#L42) to lets-encrypt. If you do explicitly specify the issuer name certificate gets created without an issue.

Please let me know if the controller should default to lets-encrypt?

**Comment by ZhiminXiang** [comment]
It depends on which ClusterIssuer we want to ship as the default Issuer, including which CA to be used, and which challenge type to be used.

From the perspective of providing good out-of-box experience, **I think** it is good to ship a ClusterIssuer with LetsEncrypt + HTTP01 challenge config (i.e. letsencrypt-http01-issuer in the [doc](letsencrypt-http01-issuer)), and set the issuerRef to point to it.

**Comment by itsmurugappan** [comment]
Am not sure if this is a bug. It is clearly mentioned in the [doc](https://knative.dev/docs/serving/using-auto-tls/) that clusterissuer needs to be created and this [config map](https://github.com/knative-sandbox/net-certmanager/blob/7c9bafdf1cd0136ae9b750ddaf9249308fbf478d/config/config.yaml#L44) needs to be updated. If we default to lets encrypt issuer in the config map, we need to create a cluster issuer with more assumptions like http01 challenge and ingress class as istio.
