### ISSUE TITLE
Bump cert-manager API version v1alpha2 -> v1

### ISSUE THREAD

**Issue by irbekrm** [knative-sandbox/net-certmanager#219]
`cert-manager` is deprecating all alpha and beta API versions in the next release (`v1.4`) (see [cert-manager#4021](https://github.com/jetstack/cert-manager/pull/4021)) and will be removing them in `v1.6`.

It might make sense to bump the API versions used in this project from `v1alpha2` -> `v1`

**Comment by omerbensaadon** [comment]
https://github.com/knative/docs/pull/3670 

Potentially closed by the above PR

**Comment by irbekrm** [comment]
> Potentially closed by the above PR

Apologies, I shouldn't have mentioned this issue in that PR- this is a separate issue.
