### ISSUE TITLE
Renewing the certificate doesn't work as expected and it will call user ksvc for 30 days 

### ISSUE THREAD

**Issue by RamyChaabane** [knative-sandbox/net-certmanager#416]
We are using cert-manager to manage ksvc certificates and I’ve noticed a weird behaviour.

Be default, cert-manager will create a certificate that will expire in 90 days, then it will try to renew it 30 days before the expiration date.

In this period and when the renew workflow is launched by cert-manager, the certificate is always in `True` state and there is no route in the ingress (we are using Kourier) is configured to forward the traffic `/.well-known/acme-challenge` coming from Lets-encrypt to `cm-acme-http-solver-xxx` pod, so all traffic is instead forwarded to the ksvc pod.

If I understand the [code of net-certmanager](https://github.com/knative-sandbox/net-certmanager/blob/main/pkg/reconciler/certificate/certificate.go#L111) correctly, we are only watching the state of the certificate, and since the certificate is in `True` state, the knative ingress will never be updated so no route will be configured

I'm opening a PR addressing this issue but I'm not `100%` sure that it will work. To reproduce the behaviour we need to wait for 60 days for the renewal process to be lanched (unless there is a workaround for that)

**Comment by nak3** [comment]
> I'm opening a PR addressing this issue but I'm not 100% sure that it will work. To reproduce the behaviour we need to wait for 60 days for the renewal process to be lanched (unless there is a workaround for that)

I guess  (Sorry I haven't tried, though :sweat_smile: ) we can modify `CertificateSpec.Duration` and `RenewBefore` to verify the code change.

https://github.com/knative-sandbox/net-certmanager/blob/aae5d3e9cebffb97ed58aa061011440038e08f67/pkg/reconciler/certificate/resources/cert_manager_certificate.go#L42

https://github.com/knative-sandbox/net-certmanager/blob/aae5d3e9cebffb97ed58aa061011440038e08f67/vendor/github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1/types_certificate.go#L102-L117

**Comment by tendant** [comment]
We have some knative service are due for renewing certificate, however there is no traffic routed to the cm-acme-http-solver. Below examples are some live pods in the same namespace as knative services. They are been listening on the port for more than 20 days. 

Any way to fix these issue other than delete existing knative services and recreate them? 

If there is any patch we can help to test this issue, we would happy to do so. 

cm-acme-http-solver-7j2fh                                         1/1     Running     0          19d
cm-acme-http-solver-9d4gs                                         1/1     Running     0          21d
cm-acme-http-solver-dgnnm                                         1/1     Running     0          19d
cm-acme-http-solver-js6vx                                         1/1     Running     0          21d

**Comment by RamyChaabane** [comment]
Hello @tendant 

Obviously I did a bad job testing the patch, so I'm revering to the [first one](https://github.com/RamyChaabane/net-certmanager/tree/detect-certificate-renewing-state) that works (it works for us and use it in production).

Please note that this patch is not perfect as it marks the Knative certificate to notReady, ie as mentioned by @dprotaso, This will transition the Ready condition from True => Unknown. This Unknown will propagate up the serving route controller and signal that the cert is not ready and things will downgrade to HTTP.

@nak3 could you please reopen the issue?

**Comment by tendant** [comment]
Thanks @RamyChaabane Is there any other way to start the cert renew process without downgrade to HTTP. We are using HTTP-01 for cert-manager, the problem is that the acme-http-resolver is not map to the serving route. If there is a way to manually add the route to ingress controller, we can make it work without downgrading to HTTP. 

Because downgrade to HTTP will have down time for the service, which is no different from deleting the service and re-creating it.

**Comment by RamyChaabane** [comment]
Hello @tendant 

Exactly, that what I was working on, but unfortunatly I can't find a way to do that. We need a further step after updating Knative certificate status with HTTP-01 challenge to reconfigure the ingress. That way, the ingress controller will watch that change and create the serving route.

I've tried to do that manually, but it doesn't work, ie the new spec config will be erased and the old one will take place, my guess is because the ingress is controlled/owned by the domain mapping resource.

I've tried to create another ingress with the same domain holding HTTP-01 route, but this didn't work as well because there will be a domain conflict.

I'm not sure, but I guess we need to kick domain mapping reconciliation (or route reconciliation) to update the ingress spec.

@nak3 @dprotaso 
What do you think about this?
Any idea on how we can do it?

**Comment by dprotaso** [comment]
My comment from #459 

Quick scan of the PR - we don't want `net-certmanager` to be programming the Ingress and pulling in these dependencies. 

There already exists a mechanism to pass the challenge details via the Certificates `Status.HTTP01Challenges` and the Serving Route controller will add the ACME Paths to the Ingress.

It just seems the Route controller doesn't handle a cert renewal case when the Cert is already ready.
https://github.com/knative/serving/blob/a4fcb9dcf510f274dcb13e92d39595047e0b8e0a/pkg/reconciler/route/route.go#L242-L246

**Comment by dprotaso** [comment]
I think if the certificate is going to expire then we'd want to

1. Set up the challenge
2. Update the Knative Certificate `Status.HTTP01Challenges` & potentially add a new condition indicating it's renewing
3. Route reconciler sees the Certificate resource change with the new challenges and will add the ACME paths to the Ingress

**Comment by dprotaso** [comment]
It looks like 1,2 are done and we just need to complete 3.

**Comment by dprotaso** [comment]
screwed up the earlier assign by having text after the name
/assign @KauzClay

**Comment by dprotaso** [comment]
Patch release is out I'm going to close this out 
https://github.com/knative-sandbox/net-certmanager/releases/tag/knative-v1.9.3
